version: '3.7'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  postgres:
    container_name: postgres
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  matchmaker:
    container_name: matchmaker-service
    build:
      context: .
      dockerfile: Dockerfile
    command: --spring.profiles.active=common
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=matchmaker.delitime.docker
      - VIRTUAL_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/matchmaker?user=postgres&password=postgres
    volumes:
      - ./:/var/www
    networks:
      - default

networks:
  default:
    external:
      name: dev-env
